# Generated by Django 5.2.9 on 2025-12-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workinghourssummary',
            name='employee',
        ),
        migrations.DeleteModel(
            name='DailyUpdate',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='WorkingHoursSummary',
        ),
    ]
